events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /users {
            proxy_pass http://user-manager:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /interests {
            proxy_pass http://data-collector:5001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /flights {
            proxy_pass http://data-collector:5001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /analysis {
            proxy_pass http://data-collector:5001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}