apiVersion: v1
kind: Secret
metadata:
  name: dsbd-secrets
type: Opaque
stringData:
  # Database
  mysql-root-password: "root_password"
  app-db-password: "app_password"
  
  # OpenSky 
  opensky-client-secret: "xxxxxxxxxxxxxxxxxxxxxxx"
  
  # App password
  smtp-password: "xxxx xxxx xxxx xxxx"