apiVersion: v1
kind: ConfigMap
metadata:
  name: sla-config
data:
  sla_config.yaml: |
    metrics:
      
      - name: "fetch_duration_sla"
        query: "last_fetch_duration_seconds"
        min: 0
        max: 5.0
      
      
      - name: "users_count_sla"
        query: "users_registered_count"
        min: 1
        max: 1000