apiVersion: v1
kind: ConfigMap
metadata:
  name: dsbd-config
data:
  # Database Configuration
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_USER: "app_user"
  DB_NAME_USER: "user_db"
  DB_NAME_DATA: "data_db"
  
  # Service Discovery
  USER_MANAGER_HOST: "user-manager-service"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  
  # API & External Services
  OPENSKY_CLIENT_ID: "provatest1-api-client"
  SMTP_SERVER: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "paololol690@gmail.com"