apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      # Job per monitorare Prometheus stesso
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # Job per User Manager
      - job_name: 'user-manager'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['user-manager-service:5000']
      
      # Job per Data Collector
      - job_name: 'data-collector'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['data-collector-service:5001']