apiVersion: v1
kind: Secret
metadata:
  name: dsbd-secrets
type: Opaque
stringData:
  # Database
  mysql-root-password: "root_password"
  app-db-password: "app_password"
  
  # OpenSky 
  opensky-client-secret: ""
  
  # Email (app password)
  smtp-password: ""